# Generated by Django 3.0.3 on 2020-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopLiked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
